### ISSUE TITLE
No local packages or download links found for PIL

### ISSUE THREAD

**Issue by fromagek** [ptomato/Beams#6]
Hello folks,
me again. After leaving beams abandoned for long time I tried install it on Linux Mint 17.3 again recently.
As described on [ptomato’s homepage](http://ptomato.name/opensource/beams/beams-download.html) I installed the packages
* `python-numpy`
* `python-scipy`
* `python-traits`
* `python-chaco`
* `python-opencv`

and `python-setuptools`.
After I downloaded Beams-0.9.rc3.zip. Running `python setup.py install`
left mw with the following error:
``` Bash
Installed /usr/local/lib/python2.7/dist-packages/Beams-0.9.rc3-py2.7.egg
Processing dependencies for Beams==0.9.rc3
Searching for PIL
Reading https://pypi.python.org/simple/PIL/
No local packages or download links found for PIL
error: Could not find suitable distribution for Requirement.parse('PIL')
```

how could I fix that?
best florian

**Comment by ptomato** [comment]
Hmm, I don't require PIL explicitly (though I'm sure it's required by one of the other dependencies), so I'm not sure where this is coming from. In any case when I install it, I do see the `Processing dependencies for Beams==0.9.rc3` message as I would normally expect, but PIL is not one of the dependencies it processes.

In any case I believe the package name for Linux Mint is `python-pil`, so you could try installing that.

**Comment by ptomato** [comment]
The recommended way to install Beams is now to use Anaconda. (See the [install instructions](http://ptomato.name/opensource/beams/beams-download.html).) This should not be a problem anymore, as Anaconda should install the correct packages.

**Comment by fromagek** [comment]
Dear Ptomato,
I tried you install instructions today on Windows 7 but got stuck at the last point with the following error.

```
...
Collecting enable (from chaco>=4->Beams==0.9rc5)
Using cached enable-4.5.1.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "c:\users\fkress\appdata\local\temp\pip-build-yscwuv\enable\setup.py", line 194, in <module>
write_version_py(filename='enable/_version.py')
File "c:\users\fkress\appdata\local\temp\pip-build-yscwuv\enable\setup.py", line 100, in write_version_py
raise ImportError("Unable to import git_revision. Try removing "
ImportError: Unable to import git_revision. Try removing kiva/_version.py and the build directory before building.

 ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\me\appdata\local\temp\pip-build-yscwuv\enable\
```

Hopefully I will get it running with your help.
Best florian

**Comment by ptomato** [comment]
Try `conda install chaco` before doing the last step?

**Comment by galian123** [comment]
try this: easy_install --find-links http://www.pythonware.com/products/pil/ Imaging
