### ISSUE TITLE
How to run beam.exe

### ISSUE THREAD

**Issue by DerekFan** [ptomato/Beams#8]
Hi Chimento,

Currently I found this project to be quite interesting, and I downloaded the release version and installed on my windows PC using python 2.7. In the end, I found beam.exe under C:\Python27\Scripts folder, but it cannot be run. If you would be so kind, could you help to tell how to run your beam program? Thanks in advance.

Best Regards,
Derek

**Comment by ptomato** [comment]
Can you explain more about what "cannot be run" means?
Did you follow the instructions for installing and running on http://ptomato.name/opensource/beams/beams-download.html? If so, then maybe you can help me figure out what needs to be changed on that page :-)

**Comment by DerekFan** [comment]
thanks for the swiftly reply :-), I did not know there is an instruction for your program. Appreciate the help, i am gonna try it again now.
